name: Q4

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: archive datée
        run: |
          DATE=$(date +'%d-%m-%Y')
          FILENAME="Q4_archive_${DATE}.txt"
          echo "Nom : CHRIKI" > $FILENAME
          echo "Prénom : Mohamed-Bilel" >> $FILENAME
          echo "" >> $FILENAME
          cat Q4.java >> $FILENAME

      - name: Commit and push
        run: |
          git config --global user.name "bilelIUT"
          git config --global user.email "bilelenplus@gmail.com"
          git add Q4_archive_*.txt
          git commit -m "Ajout de l’archive Q4 avec date"
          git push
