name: Q6

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: archives datée
        run: |
          DATE=$(date +'%d-%m-%Y-%H%M%S')
          FILENAME="Q6_archive_${DATE}.txt"
          echo "Nom : CHRIKI" > $FILENAME
          echo "Prénom : Mohamed-Bilel" >> $FILENAME
          echo "" >> $FILENAME
          cat Q6.java >> $FILENAME
          echo "" >> $FILENAME
          echo "Lignes et caractères de Q6" >> $FILENAME
          wc -l -m Q6.java >> $ARCHIVE

      - name: Commit and push
        run: |
          git config --global user.name "bilelIUT"
          git config --global user.email "bilelenplus@gmail.com"
          git add Q6_archive_*.txt
          git commit -m "Ajout de l’archive Q6 avec date"
          git push
